name: 'fraud_analytics'
version: '1.0.0'
config-version: 2

profile: 'fraud_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  fraud_analytics:
    +schema: seeds

vars:
  high_risk_threshold: 0.1
  medium_risk_threshold: 0.05
  large_transaction_threshold: 500
